config/routes.rb
Izool::Application.routes.draw do
  get "cityhunter/index"

  devise_for :accounts

  get "home/index"

  root :to => "home#index"

end

app/models/account.rb
class Account < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable, :lockable and :timeoutable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_filter :authenticate_account!

  protect_from_forgery
end

app/controllers/cityhunter_controller.rb
class CityhunterController < ApplicationController
  def index
    if Rails.env.production?
      @geo = GeoIp.geolocation(current_account.current_sign_in_ip)
    else
      @geo = GeoIp.geolocation('58.246.55.174')
    end
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cityhunter_helper.rb
module CityhunterHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/cityhunter/index.html.haml
%h1= @geo.inspect

app/views/home/index.html.haml
欢迎您,

点击进入
=link_to("<<城市猎人>>", cityhunter_index_path)

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en" class="no-js">
<head>
  <meta charset="utf-8">

  <!-- www.phpied.com/conditional-comments-block-downloads/ -->
  <!--[if IE]><![endif]-->

  <!-- Always force latest IE rendering engine (even in intranet) & Chrome Frame 
       Remove this if you use the .htaccess -->
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

  <title>Izool</title>
  <meta name="description" content="">
  <meta name="author" content="">

  <!--  Mobile viewport optimized: j.mp/bplateviewport -->
  <meta name="viewport" content="width=device-width; initial-scale=1.0">

  <!-- Replace favicon.ico & apple-touch-icon.png in the root of your domain and delete these references -->
  <link rel="shortcut icon" href="/favicon.ico">
  <link rel="apple-touch-icon" href="/apple-touch-icon.png">


  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>


  <%= csrf_meta_tag %>
  <%= javascript_include_tag "modernizr-1.5.min.js"%>

</head>

<!-- paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/ -->

<!--[if lt IE 7 ]> <body class="ie6"> <![endif]-->
<!--[if IE 7 ]>    <body class="ie7"> <![endif]-->
<!--[if IE 8 ]>    <body class="ie8"> <![endif]-->
<!--[if IE 9 ]>    <body class="ie9"> <![endif]-->
<!--[if (gt IE 9)|!(IE)]><!--> <body> <!--<![endif]-->

  <div id="container">
    <header>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    </header>
    
    <div id="main">
      <%= yield %>
    </div>
    
    <footer>

    </footer>
  </div> <!--! end of #container -->


  <!-- Javascript at the bottom for fast page loading -->

  <!-- Grab Google CDN's jQuery. fall back to local if necessary -->
  <!-- <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.4.2/jquery.min.js"></script> 
  <script>!window.jQuery && document.write('<script src="javascripts/jquery-1.4.2.min.js"><\/script>')</script>-->
  <%= javascript_include_tag "jquery-1.4.2.min" %>
  <%= javascript_include_tag "plugins" %>
  <%= javascript_include_tag "script" %>

  <!--[if lt IE 7 ]>
    <script src="js/dd_belatedpng.js?v=1"></script>
  <![endif]-->


  <!-- yui profiler and profileviewer - remove for production -->
  <!-- <script src="js/profiling/yahoo-profiling.min.js?v=1"></script>
  <script src="js/profiling/config.js?v=1"></script> -->
  <!-- end profiling code -->


  <!-- asynchronous google analytics: mathiasbynens.be/notes/async-analytics-snippet 
       change the UA-XXXXX-X to be your site's ID -->
  <!-- <script>
   var _gaq = [['_setAccount', 'UA-XXXXX-X'], ['_trackPageview']];
   (function(d, t) {
    var g = d.createElement(t),
        s = d.getElementsByTagName(t)[0];
    g.async = true;
    g.src = ('https:' == location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    s.parentNode.insertBefore(g, s);
   })(document, 'script');
  </script>
  -->
  
</body>
</html>